#!/usr/bin/env bash
# Does what 4-to_infinity_and_beyond does
# But prints I am invincible!!! when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" 15
while true;
do
	echo "To infinity and beyond";
	sleep 2
done
