#!/usr/bin/env bash
# Loops from 1 to 10
# Displays "bad luck" for 4th loop iteration
# Displays "good luck" for 8th loop iteration
# Displays "Best School" for every other iteration
count=0
while [ $count -lt 10 ] 
do
	if [ $count -eq 3 ]
	then
		echo "bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( count++ ))
done
