#!/usr/bin/env bash
# 4 and then "bad luck from China" for 4th iteration
# 9 and then "bad luck from Japan" for 9th loop
# 17 and then "bad luck from Italy" for 17th iteration
# uses while loop and case statement
count=1
while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
